//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/uni_study/2.2/metrology/parser/.vscode/Swift5Parser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Swift5Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISwift5ParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.top_level"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop_level([NotNull] Swift5Parser.Top_levelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] Swift5Parser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] Swift5Parser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop_statement([NotNull] Swift5Parser.Loop_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.for_in_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_in_statement([NotNull] Swift5Parser.For_in_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] Swift5Parser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.condition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_list([NotNull] Swift5Parser.Condition_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] Swift5Parser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.case_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_condition([NotNull] Swift5Parser.Case_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.optional_binding_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptional_binding_condition([NotNull] Swift5Parser.Optional_binding_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.repeat_while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat_while_statement([NotNull] Swift5Parser.Repeat_while_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.branch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBranch_statement([NotNull] Swift5Parser.Branch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] Swift5Parser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_clause([NotNull] Swift5Parser.Else_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.guard_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuard_statement([NotNull] Swift5Parser.Guard_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] Swift5Parser.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.switch_cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_cases([NotNull] Swift5Parser.Switch_casesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.switch_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_case([NotNull] Swift5Parser.Switch_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.case_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_label([NotNull] Swift5Parser.Case_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.case_item_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_item_list([NotNull] Swift5Parser.Case_item_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.default_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_label([NotNull] Swift5Parser.Default_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_clause([NotNull] Swift5Parser.Where_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.where_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_expression([NotNull] Swift5Parser.Where_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.conditional_switch_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_switch_case([NotNull] Swift5Parser.Conditional_switch_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.switch_if_directive_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_if_directive_clause([NotNull] Swift5Parser.Switch_if_directive_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.switch_elseif_directive_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_elseif_directive_clauses([NotNull] Swift5Parser.Switch_elseif_directive_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.switch_elseif_directive_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_elseif_directive_clause([NotNull] Swift5Parser.Switch_elseif_directive_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.switch_else_directive_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_else_directive_clause([NotNull] Swift5Parser.Switch_else_directive_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.labeled_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeled_statement([NotNull] Swift5Parser.Labeled_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.statement_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_label([NotNull] Swift5Parser.Statement_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.label_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_name([NotNull] Swift5Parser.Label_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.control_transfer_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControl_transfer_statement([NotNull] Swift5Parser.Control_transfer_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.break_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_statement([NotNull] Swift5Parser.Break_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.continue_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinue_statement([NotNull] Swift5Parser.Continue_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.fallthrough_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFallthrough_statement([NotNull] Swift5Parser.Fallthrough_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] Swift5Parser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrow_statement([NotNull] Swift5Parser.Throw_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.defer_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefer_statement([NotNull] Swift5Parser.Defer_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.do_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDo_statement([NotNull] Swift5Parser.Do_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.catch_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_clauses([NotNull] Swift5Parser.Catch_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_clause([NotNull] Swift5Parser.Catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.catch_pattern_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_pattern_list([NotNull] Swift5Parser.Catch_pattern_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.catch_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_pattern([NotNull] Swift5Parser.Catch_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.compiler_control_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompiler_control_statement([NotNull] Swift5Parser.Compiler_control_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.conditional_compilation_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_compilation_block([NotNull] Swift5Parser.Conditional_compilation_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.if_directive_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_directive_clause([NotNull] Swift5Parser.If_directive_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.elseif_directive_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseif_directive_clauses([NotNull] Swift5Parser.Elseif_directive_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.elseif_directive_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseif_directive_clause([NotNull] Swift5Parser.Elseif_directive_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.else_directive_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_directive_clause([NotNull] Swift5Parser.Else_directive_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.compilation_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_condition([NotNull] Swift5Parser.Compilation_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.platform_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlatform_condition([NotNull] Swift5Parser.Platform_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.swift_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwift_version([NotNull] Swift5Parser.Swift_versionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.swift_version_continuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwift_version_continuation([NotNull] Swift5Parser.Swift_version_continuationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.operating_system"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperating_system([NotNull] Swift5Parser.Operating_systemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.architecture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture([NotNull] Swift5Parser.ArchitectureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_name([NotNull] Swift5Parser.Module_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.environment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnvironment([NotNull] Swift5Parser.EnvironmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.line_control_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine_control_statement([NotNull] Swift5Parser.Line_control_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.line_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine_number([NotNull] Swift5Parser.Line_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.file_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_name([NotNull] Swift5Parser.File_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.diagnostic_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiagnostic_statement([NotNull] Swift5Parser.Diagnostic_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.diagnostic_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiagnostic_message([NotNull] Swift5Parser.Diagnostic_messageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.availability_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAvailability_condition([NotNull] Swift5Parser.Availability_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.availability_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAvailability_arguments([NotNull] Swift5Parser.Availability_argumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.availability_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAvailability_argument([NotNull] Swift5Parser.Availability_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.platform_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlatform_name([NotNull] Swift5Parser.Platform_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.platform_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlatform_version([NotNull] Swift5Parser.Platform_versionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.generic_parameter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_parameter_clause([NotNull] Swift5Parser.Generic_parameter_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.generic_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_parameter_list([NotNull] Swift5Parser.Generic_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.generic_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_parameter([NotNull] Swift5Parser.Generic_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.generic_where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_where_clause([NotNull] Swift5Parser.Generic_where_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.requirement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequirement_list([NotNull] Swift5Parser.Requirement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequirement([NotNull] Swift5Parser.RequirementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.conformance_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConformance_requirement([NotNull] Swift5Parser.Conformance_requirementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.same_type_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSame_type_requirement([NotNull] Swift5Parser.Same_type_requirementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.generic_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_argument_clause([NotNull] Swift5Parser.Generic_argument_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.generic_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_argument_list([NotNull] Swift5Parser.Generic_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.generic_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_argument([NotNull] Swift5Parser.Generic_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] Swift5Parser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarations([NotNull] Swift5Parser.DeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.top_level_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop_level_declaration([NotNull] Swift5Parser.Top_level_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.code_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode_block([NotNull] Swift5Parser.Code_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.import_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_declaration([NotNull] Swift5Parser.Import_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.import_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_kind([NotNull] Swift5Parser.Import_kindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.import_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_path([NotNull] Swift5Parser.Import_pathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.import_path_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_path_identifier([NotNull] Swift5Parser.Import_path_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declaration([NotNull] Swift5Parser.Constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.pattern_initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern_initializer_list([NotNull] Swift5Parser.Pattern_initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.pattern_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern_initializer([NotNull] Swift5Parser.Pattern_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] Swift5Parser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration([NotNull] Swift5Parser.Variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.variable_declaration_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration_head([NotNull] Swift5Parser.Variable_declaration_headContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.variable_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_name([NotNull] Swift5Parser.Variable_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.getter_setter_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetter_setter_block([NotNull] Swift5Parser.Getter_setter_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.getter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetter_clause([NotNull] Swift5Parser.Getter_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.setter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetter_clause([NotNull] Swift5Parser.Setter_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.setter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetter_name([NotNull] Swift5Parser.Setter_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.getter_setter_keyword_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetter_setter_keyword_block([NotNull] Swift5Parser.Getter_setter_keyword_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.getter_keyword_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetter_keyword_clause([NotNull] Swift5Parser.Getter_keyword_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.setter_keyword_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetter_keyword_clause([NotNull] Swift5Parser.Setter_keyword_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.willSet_didSet_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWillSet_didSet_block([NotNull] Swift5Parser.WillSet_didSet_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.willSet_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWillSet_clause([NotNull] Swift5Parser.WillSet_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.didSet_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDidSet_clause([NotNull] Swift5Parser.DidSet_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.typealias_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypealias_declaration([NotNull] Swift5Parser.Typealias_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.typealias_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypealias_name([NotNull] Swift5Parser.Typealias_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.typealias_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypealias_assignment([NotNull] Swift5Parser.Typealias_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_declaration([NotNull] Swift5Parser.Function_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_head([NotNull] Swift5Parser.Function_headContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] Swift5Parser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_signature([NotNull] Swift5Parser.Function_signatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_result([NotNull] Swift5Parser.Function_resultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_body([NotNull] Swift5Parser.Function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.parameter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_clause([NotNull] Swift5Parser.Parameter_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_list([NotNull] Swift5Parser.Parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] Swift5Parser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.external_parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_parameter_name([NotNull] Swift5Parser.External_parameter_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.local_parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_parameter_name([NotNull] Swift5Parser.Local_parameter_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.default_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_argument_clause([NotNull] Swift5Parser.Default_argument_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.enum_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_declaration([NotNull] Swift5Parser.Enum_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.union_style_enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_style_enum([NotNull] Swift5Parser.Union_style_enumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.union_style_enum_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_style_enum_members([NotNull] Swift5Parser.Union_style_enum_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.union_style_enum_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_style_enum_member([NotNull] Swift5Parser.Union_style_enum_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.union_style_enum_case_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_style_enum_case_clause([NotNull] Swift5Parser.Union_style_enum_case_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.union_style_enum_case_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_style_enum_case_list([NotNull] Swift5Parser.Union_style_enum_case_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.union_style_enum_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_style_enum_case([NotNull] Swift5Parser.Union_style_enum_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.enum_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_name([NotNull] Swift5Parser.Enum_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.enum_case_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_case_name([NotNull] Swift5Parser.Enum_case_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_style_enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_style_enum([NotNull] Swift5Parser.Raw_value_style_enumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_style_enum_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_style_enum_members([NotNull] Swift5Parser.Raw_value_style_enum_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_style_enum_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_style_enum_member([NotNull] Swift5Parser.Raw_value_style_enum_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_style_enum_case_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_style_enum_case_clause([NotNull] Swift5Parser.Raw_value_style_enum_case_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_style_enum_case_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_style_enum_case_list([NotNull] Swift5Parser.Raw_value_style_enum_case_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_style_enum_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_style_enum_case([NotNull] Swift5Parser.Raw_value_style_enum_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_assignment([NotNull] Swift5Parser.Raw_value_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.raw_value_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_value_literal([NotNull] Swift5Parser.Raw_value_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declaration([NotNull] Swift5Parser.Struct_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.struct_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_name([NotNull] Swift5Parser.Struct_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.struct_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_body([NotNull] Swift5Parser.Struct_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.struct_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_members([NotNull] Swift5Parser.Struct_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.struct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_member([NotNull] Swift5Parser.Struct_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.class_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_declaration([NotNull] Swift5Parser.Class_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_name([NotNull] Swift5Parser.Class_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_body([NotNull] Swift5Parser.Class_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.class_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_members([NotNull] Swift5Parser.Class_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_member([NotNull] Swift5Parser.Class_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_declaration([NotNull] Swift5Parser.Protocol_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_name([NotNull] Swift5Parser.Protocol_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_body([NotNull] Swift5Parser.Protocol_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_members([NotNull] Swift5Parser.Protocol_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_member([NotNull] Swift5Parser.Protocol_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_member_declaration([NotNull] Swift5Parser.Protocol_member_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_property_declaration([NotNull] Swift5Parser.Protocol_property_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_method_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_method_declaration([NotNull] Swift5Parser.Protocol_method_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_initializer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_initializer_declaration([NotNull] Swift5Parser.Protocol_initializer_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_subscript_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_subscript_declaration([NotNull] Swift5Parser.Protocol_subscript_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_associated_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_associated_type_declaration([NotNull] Swift5Parser.Protocol_associated_type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.initializer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_declaration([NotNull] Swift5Parser.Initializer_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.initializer_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_head([NotNull] Swift5Parser.Initializer_headContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.initializer_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_body([NotNull] Swift5Parser.Initializer_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.deinitializer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeinitializer_declaration([NotNull] Swift5Parser.Deinitializer_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.extension_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_declaration([NotNull] Swift5Parser.Extension_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.extension_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_body([NotNull] Swift5Parser.Extension_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.extension_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_members([NotNull] Swift5Parser.Extension_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.extension_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_member([NotNull] Swift5Parser.Extension_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.subscript_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript_declaration([NotNull] Swift5Parser.Subscript_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.subscript_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript_head([NotNull] Swift5Parser.Subscript_headContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.subscript_result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript_result([NotNull] Swift5Parser.Subscript_resultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_declaration([NotNull] Swift5Parser.Operator_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.prefix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefix_operator_declaration([NotNull] Swift5Parser.Prefix_operator_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.postfix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_operator_declaration([NotNull] Swift5Parser.Postfix_operator_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.infix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInfix_operator_declaration([NotNull] Swift5Parser.Infix_operator_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.infix_operator_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInfix_operator_group([NotNull] Swift5Parser.Infix_operator_groupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_declaration([NotNull] Swift5Parser.Precedence_group_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_attributes([NotNull] Swift5Parser.Precedence_group_attributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_attribute([NotNull] Swift5Parser.Precedence_group_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_relation([NotNull] Swift5Parser.Precedence_group_relationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_assignment([NotNull] Swift5Parser.Precedence_group_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_associativity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_associativity([NotNull] Swift5Parser.Precedence_group_associativityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_names([NotNull] Swift5Parser.Precedence_group_namesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.precedence_group_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecedence_group_name([NotNull] Swift5Parser.Precedence_group_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.declaration_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration_modifier([NotNull] Swift5Parser.Declaration_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.declaration_modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration_modifiers([NotNull] Swift5Parser.Declaration_modifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.access_level_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_level_modifier([NotNull] Swift5Parser.Access_level_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.mutation_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMutation_modifier([NotNull] Swift5Parser.Mutation_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern([NotNull] Swift5Parser.PatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.wildcard_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcard_pattern([NotNull] Swift5Parser.Wildcard_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.identifier_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_pattern([NotNull] Swift5Parser.Identifier_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.value_binding_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_binding_pattern([NotNull] Swift5Parser.Value_binding_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_pattern([NotNull] Swift5Parser.Tuple_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_pattern_element_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_pattern_element_list([NotNull] Swift5Parser.Tuple_pattern_element_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_pattern_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_pattern_element([NotNull] Swift5Parser.Tuple_pattern_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.enum_case_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_case_pattern([NotNull] Swift5Parser.Enum_case_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.optional_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptional_pattern([NotNull] Swift5Parser.Optional_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.expression_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_pattern([NotNull] Swift5Parser.Expression_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] Swift5Parser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.attribute_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_name([NotNull] Swift5Parser.Attribute_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.attribute_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_argument_clause([NotNull] Swift5Parser.Attribute_argument_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] Swift5Parser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.balanced_tokens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalanced_tokens([NotNull] Swift5Parser.Balanced_tokensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.balanced_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalanced_token([NotNull] Swift5Parser.Balanced_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.balanced_token_punctuation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalanced_token_punctuation([NotNull] Swift5Parser.Balanced_token_punctuationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] Swift5Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_list([NotNull] Swift5Parser.Expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.prefix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefix_expression([NotNull] Swift5Parser.Prefix_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.in_out_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_out_expression([NotNull] Swift5Parser.In_out_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.try_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTry_operator([NotNull] Swift5Parser.Try_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.binary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_expression([NotNull] Swift5Parser.Binary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.binary_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_expressions([NotNull] Swift5Parser.Binary_expressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.conditional_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_operator([NotNull] Swift5Parser.Conditional_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.type_casting_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_casting_operator([NotNull] Swift5Parser.Type_casting_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] Swift5Parser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.unqualified_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnqualified_name([NotNull] Swift5Parser.Unqualified_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.literal_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral_expression([NotNull] Swift5Parser.Literal_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.array_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_literal([NotNull] Swift5Parser.Array_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.array_literal_items"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_literal_items([NotNull] Swift5Parser.Array_literal_itemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.array_literal_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_literal_item([NotNull] Swift5Parser.Array_literal_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.dictionary_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionary_literal([NotNull] Swift5Parser.Dictionary_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.dictionary_literal_items"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionary_literal_items([NotNull] Swift5Parser.Dictionary_literal_itemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.dictionary_literal_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionary_literal_item([NotNull] Swift5Parser.Dictionary_literal_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.playground_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlayground_literal([NotNull] Swift5Parser.Playground_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>self_pure_expression</c>
	/// labeled alternative in <see cref="Swift5Parser.self_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelf_pure_expression([NotNull] Swift5Parser.Self_pure_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>self_method_expression</c>
	/// labeled alternative in <see cref="Swift5Parser.self_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelf_method_expression([NotNull] Swift5Parser.Self_method_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>self_subscript_expression</c>
	/// labeled alternative in <see cref="Swift5Parser.self_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelf_subscript_expression([NotNull] Swift5Parser.Self_subscript_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>self_initializer_expression</c>
	/// labeled alternative in <see cref="Swift5Parser.self_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelf_initializer_expression([NotNull] Swift5Parser.Self_initializer_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>superclass_method_expression</c>
	/// labeled alternative in <see cref="Swift5Parser.superclass_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperclass_method_expression([NotNull] Swift5Parser.Superclass_method_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>superclass_subscript_expression</c>
	/// labeled alternative in <see cref="Swift5Parser.superclass_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperclass_subscript_expression([NotNull] Swift5Parser.Superclass_subscript_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>superclass_initializer_expression</c>
	/// labeled alternative in <see cref="Swift5Parser.superclass_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperclass_initializer_expression([NotNull] Swift5Parser.Superclass_initializer_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.closure_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosure_expression([NotNull] Swift5Parser.Closure_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.closure_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosure_signature([NotNull] Swift5Parser.Closure_signatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.closure_parameter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosure_parameter_clause([NotNull] Swift5Parser.Closure_parameter_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.closure_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosure_parameter_list([NotNull] Swift5Parser.Closure_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.closure_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosure_parameter([NotNull] Swift5Parser.Closure_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.capture_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture_list([NotNull] Swift5Parser.Capture_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.capture_list_items"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture_list_items([NotNull] Swift5Parser.Capture_list_itemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.capture_list_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture_list_item([NotNull] Swift5Parser.Capture_list_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.capture_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture_specifier([NotNull] Swift5Parser.Capture_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.implicit_member_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicit_member_expression([NotNull] Swift5Parser.Implicit_member_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.parenthesized_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized_operator([NotNull] Swift5Parser.Parenthesized_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.parenthesized_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized_expression([NotNull] Swift5Parser.Parenthesized_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_expression([NotNull] Swift5Parser.Tuple_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_element_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_element_list([NotNull] Swift5Parser.Tuple_element_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_element([NotNull] Swift5Parser.Tuple_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.wildcard_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcard_expression([NotNull] Swift5Parser.Wildcard_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.key_path_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_path_expression([NotNull] Swift5Parser.Key_path_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.key_path_components"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_path_components([NotNull] Swift5Parser.Key_path_componentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.key_path_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_path_component([NotNull] Swift5Parser.Key_path_componentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.key_path_postfixes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_path_postfixes([NotNull] Swift5Parser.Key_path_postfixesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.key_path_postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_path_postfix([NotNull] Swift5Parser.Key_path_postfixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.selector_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector_expression([NotNull] Swift5Parser.Selector_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.key_path_string_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_path_string_expression([NotNull] Swift5Parser.Key_path_string_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_expression([NotNull] Swift5Parser.Postfix_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_call_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_suffix([NotNull] Swift5Parser.Function_call_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.initializer_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_suffix([NotNull] Swift5Parser.Initializer_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.explicit_member_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_member_suffix([NotNull] Swift5Parser.Explicit_member_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.postfix_self_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_self_suffix([NotNull] Swift5Parser.Postfix_self_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.subscript_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript_suffix([NotNull] Swift5Parser.Subscript_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.forced_value_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForced_value_suffix([NotNull] Swift5Parser.Forced_value_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.optional_chaining_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptional_chaining_suffix([NotNull] Swift5Parser.Optional_chaining_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_call_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_argument_clause([NotNull] Swift5Parser.Function_call_argument_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_call_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_argument_list([NotNull] Swift5Parser.Function_call_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_call_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_argument([NotNull] Swift5Parser.Function_call_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.trailing_closures"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailing_closures([NotNull] Swift5Parser.Trailing_closuresContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.labeled_trailing_closures"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeled_trailing_closures([NotNull] Swift5Parser.Labeled_trailing_closuresContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.labeled_trailing_closure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeled_trailing_closure([NotNull] Swift5Parser.Labeled_trailing_closureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.argument_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_names([NotNull] Swift5Parser.Argument_namesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.argument_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_name([NotNull] Swift5Parser.Argument_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] Swift5Parser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.type_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_annotation([NotNull] Swift5Parser.Type_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.type_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_identifier([NotNull] Swift5Parser.Type_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] Swift5Parser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_type([NotNull] Swift5Parser.Tuple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_type_element_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_type_element_list([NotNull] Swift5Parser.Tuple_type_element_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.tuple_type_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_type_element([NotNull] Swift5Parser.Tuple_type_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.element_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_name([NotNull] Swift5Parser.Element_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_type([NotNull] Swift5Parser.Function_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_type_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_type_argument_clause([NotNull] Swift5Parser.Function_type_argument_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_type_argument_list([NotNull] Swift5Parser.Function_type_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.function_type_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_type_argument([NotNull] Swift5Parser.Function_type_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.argument_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_label([NotNull] Swift5Parser.Argument_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type([NotNull] Swift5Parser.Array_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.dictionary_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionary_type([NotNull] Swift5Parser.Dictionary_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.protocol_composition_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocol_composition_type([NotNull] Swift5Parser.Protocol_composition_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.trailing_composition_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailing_composition_and([NotNull] Swift5Parser.Trailing_composition_andContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.opaque_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpaque_type([NotNull] Swift5Parser.Opaque_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.any_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_type([NotNull] Swift5Parser.Any_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.self_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelf_type([NotNull] Swift5Parser.Self_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.type_inheritance_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_inheritance_clause([NotNull] Swift5Parser.Type_inheritance_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.type_inheritance_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_inheritance_list([NotNull] Swift5Parser.Type_inheritance_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] Swift5Parser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_list([NotNull] Swift5Parser.Identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] Swift5Parser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] Swift5Parser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.negate_prefix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegate_prefix_operator([NotNull] Swift5Parser.Negate_prefix_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.compilation_condition_AND"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_condition_AND([NotNull] Swift5Parser.Compilation_condition_ANDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.compilation_condition_OR"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_condition_OR([NotNull] Swift5Parser.Compilation_condition_ORContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.compilation_condition_GE"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_condition_GE([NotNull] Swift5Parser.Compilation_condition_GEContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.compilation_condition_L"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_condition_L([NotNull] Swift5Parser.Compilation_condition_LContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.arrow_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrow_operator([NotNull] Swift5Parser.Arrow_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.range_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_operator([NotNull] Swift5Parser.Range_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.same_type_equals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSame_type_equals([NotNull] Swift5Parser.Same_type_equalsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.binary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_operator([NotNull] Swift5Parser.Binary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.prefix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefix_operator([NotNull] Swift5Parser.Prefix_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.postfix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_operator([NotNull] Swift5Parser.Postfix_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator([NotNull] Swift5Parser.OperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.operator_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_head([NotNull] Swift5Parser.Operator_headContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.operator_character"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_character([NotNull] Swift5Parser.Operator_characterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.operator_characters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_characters([NotNull] Swift5Parser.Operator_charactersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.dot_operator_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDot_operator_head([NotNull] Swift5Parser.Dot_operator_headContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.dot_operator_character"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDot_operator_character([NotNull] Swift5Parser.Dot_operator_characterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.dot_operator_characters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDot_operator_characters([NotNull] Swift5Parser.Dot_operator_charactersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] Swift5Parser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_literal([NotNull] Swift5Parser.Numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_literal([NotNull] Swift5Parser.Boolean_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.nil_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNil_literal([NotNull] Swift5Parser.Nil_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.integer_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger_literal([NotNull] Swift5Parser.Integer_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_literal([NotNull] Swift5Parser.String_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.extended_string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtended_string_literal([NotNull] Swift5Parser.Extended_string_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.static_string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatic_string_literal([NotNull] Swift5Parser.Static_string_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Swift5Parser.interpolated_string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolated_string_literal([NotNull] Swift5Parser.Interpolated_string_literalContext context);
}
